// Generated by IcedCoffeeScript 108.0.13

/*
* File: device-details-component-directive
* User: David
* Date: 2019/12/23
* Desc:
 */
if (typeof define !== 'function') { var define = require('amdefine')(module) };
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['../base-directive', 'text!./style.css', 'text!./view.html', 'underscore', "moment"], function(base, css, view, _, moment) {
  var DeviceDetailsComponentDirective, exports;
  DeviceDetailsComponentDirective = (function(_super) {
    __extends(DeviceDetailsComponentDirective, _super);

    function DeviceDetailsComponentDirective($timeout, $window, $compile, $routeParams, commonService) {
      this.show = __bind(this.show, this);
      this.id = "device-details-component";
      DeviceDetailsComponentDirective.__super__.constructor.call(this, $timeout, $window, $compile, $routeParams, commonService);
    }

    DeviceDetailsComponentDirective.prototype.setScope = function() {};

    DeviceDetailsComponentDirective.prototype.setCSS = function() {
      return css;
    };

    DeviceDetailsComponentDirective.prototype.setTemplate = function() {
      return view;
    };

    DeviceDetailsComponentDirective.prototype.show = function(scope, element, attrs) {};

    DeviceDetailsComponentDirective.prototype.resize = function(scope) {};

    DeviceDetailsComponentDirective.prototype.dispose = function(scope) {};

    return DeviceDetailsComponentDirective;

  })(base.BaseDirective);
  return exports = {
    DeviceDetailsComponentDirective: DeviceDetailsComponentDirective
  };
});
