// Generated by IcedCoffeeScript 108.0.13

/*
* File: station-info-directive
* User: David
* Date: 2019/12/24
* Desc:
 */
if (typeof define !== 'function') { var define = require('amdefine')(module) };
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['../base-directive', 'text!./style.css', 'text!./view.html', 'underscore', "moment"], function(base, css, view, _, moment) {
  var StationInfoDirective, exports;
  StationInfoDirective = (function(_super) {
    __extends(StationInfoDirective, _super);

    function StationInfoDirective($timeout, $window, $compile, $routeParams, commonService) {
      this.show = __bind(this.show, this);
      this.id = "station-info";
      StationInfoDirective.__super__.constructor.call(this, $timeout, $window, $compile, $routeParams, commonService);
    }

    StationInfoDirective.prototype.setScope = function() {};

    StationInfoDirective.prototype.setCSS = function() {
      return css;
    };

    StationInfoDirective.prototype.setTemplate = function() {
      return view;
    };

    StationInfoDirective.prototype.show = function(scope, element, attrs) {
      var stationImgUrl;
      stationImgUrl = "images/" + scope.station.model.station + ".png";
      scope.bg = this.getComponentPath(stationImgUrl);
      return console.log(scope.bg);
    };

    StationInfoDirective.prototype.resize = function(scope) {};

    StationInfoDirective.prototype.dispose = function(scope) {};

    return StationInfoDirective;

  })(base.BaseDirective);
  return exports = {
    StationInfoDirective: StationInfoDirective
  };
});
