// Generated by IcedCoffeeScript 108.0.13

/*
* File: stream-origin-voice-directive
* User: David
* Date: 2020/03/19
* Desc:
 */
if (typeof define !== 'function') { var define = require('amdefine')(module) };
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['../base-directive', 'text!./style.css', 'text!./view.html', 'underscore', "moment"], function(base, css, view, _, moment) {
  var StreamOriginVoiceDirective, exports;
  StreamOriginVoiceDirective = (function(_super) {
    __extends(StreamOriginVoiceDirective, _super);

    function StreamOriginVoiceDirective($timeout, $window, $compile, $routeParams, commonService) {
      this.show = __bind(this.show, this);
      this.id = "stream-origin-voice";
      StreamOriginVoiceDirective.__super__.constructor.call(this, $timeout, $window, $compile, $routeParams, commonService);
    }

    StreamOriginVoiceDirective.prototype.setScope = function() {};

    StreamOriginVoiceDirective.prototype.setCSS = function() {
      return css;
    };

    StreamOriginVoiceDirective.prototype.setTemplate = function() {
      return view;
    };

    StreamOriginVoiceDirective.prototype.show = function(scope, element, attrs) {};

    StreamOriginVoiceDirective.prototype.resize = function(scope) {};

    StreamOriginVoiceDirective.prototype.dispose = function(scope) {};

    return StreamOriginVoiceDirective;

  })(base.BaseDirective);
  return exports = {
    StreamOriginVoiceDirective: StreamOriginVoiceDirective
  };
});
