// Generated by IcedCoffeeScript 108.0.13

/*
* File: station-overview-map-directive
* User: David
* Date: 2020/02/26
* Desc:
 */
if (typeof define !== 'function') { var define = require('amdefine')(module) };
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['../base-directive', 'text!./style.css', 'text!./view.html', 'underscore', "moment"], function(base, css, view, _, moment) {
  var StationOverviewMapDirective, exports;
  StationOverviewMapDirective = (function(_super) {
    __extends(StationOverviewMapDirective, _super);

    function StationOverviewMapDirective($timeout, $window, $compile, $routeParams, commonService) {
      this.show = __bind(this.show, this);
      this.id = "station-overview-map";
      StationOverviewMapDirective.__super__.constructor.call(this, $timeout, $window, $compile, $routeParams, commonService);
    }

    StationOverviewMapDirective.prototype.setScope = function() {};

    StationOverviewMapDirective.prototype.setCSS = function() {
      return css;
    };

    StationOverviewMapDirective.prototype.setTemplate = function() {
      return view;
    };

    StationOverviewMapDirective.prototype.show = function(scope, element, attrs) {};

    StationOverviewMapDirective.prototype.resize = function(scope) {};

    StationOverviewMapDirective.prototype.dispose = function(scope) {};

    return StationOverviewMapDirective;

  })(base.BaseDirective);
  return exports = {
    StationOverviewMapDirective: StationOverviewMapDirective
  };
});
